### PR TITLE
change: Update to Loom mappings 23w12a+build.1

### PR DESCRIPTION
**Pull request by 5HT2**
This build currently works and runs fine, I will try to remember to update this when 1.20 releases fully (please ping me if my pull request has not been updated on release day).

I'm not expecting this to be merged, but I hope it is of convenience for anyone who would like to use phosphor on the latest snapshot.

### CODE REVIEW

**Comment by 5HT2** [comment]
Oh.. I didn't realize this snapshot came out literally yesterday.

I'm having difficulty porting Sodium to the new snapshot because it looks like `RenderManager.disableTexture()` (and `enableTexture()`)was entirely removed, as was the underlying GLStateManager method it called.

Would you mind explaining (in GL terms) what that was doing @jellysquid3?

As far as I can tell it was used to disable the current active texture, and re-enable it when done with Sodium's methods.

Right now I'm unsure if this behavior is strictly necessary to *keep* for Sodium, and if the references to those methods should just be removed, or if I should implement accessors for `GLStateManager.TEXTURES` and `GLStateManager.activeTexture` to re-add this behavior.

I understand you're probably very busy / maintaining these projects isn't at the top of your priority list, I don't mind helping port things and fix bugs, as I've had a lot of experience doing that in previous mods ([kami-blue/client](https://github.com/kami-blue/client) in particular had a lot of patches and Mixins to fix or replace Minecraft's original terrible rendering code, and to get Optifine + other things to work well with it).

And, if it is more appropriate, I can open a draft PR or issue in Sodium instead, or contact you elsewhere (my own contacts are listed on [frogg.ie](https://frogg.ie)).

Thank you! :)

**Comment by IMS212** [comment]
@5HT2 There is already a Sodium port; check the 1.20/dev branch.

**Comment by 5HT2** [comment]
Omg I didn't see that when I started working on it lol.

That's fantastic to know, thank you. Are you able to make a `1.20/dev` branch in this repo? You can switch my pull request to that branch once you have.

This pull request works just fine on the latest snapshot builds.

**Comment by IMS212** [comment]
I do not control Lithium and Phosphor, so no. However, I don't think this is required to run it.

**Pull request closed without merging**
