### PR TITLE
Updated to 1.17

### PR DESCRIPTION
**Pull request by Ceebox**
This compiles and runs.

### CODE REVIEW

**Comment by 2No2Name** [comment]
Does it work ?

**Comment by Wyvest** [comment]
oh man a pull request with 4 lines of code changed will definitely work on 1.17, an update that majorly changes the rendering code will work!

**Comment by Nadeem-05** [comment]
yeah no i dont think changing the version in gradle properties isnt gonna work

**Comment by jellysquid3** [comment]
See discussion on Discord [here](https://discord.com/channels/602796788608401408/602796788608401410/851883219016351754). Porting is obviously more complex than this, otherwise we would've already had a new release out.

**Pull request closed without merging**
